### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by XuyuEre**
fix one error

### CODE REVIEW

**Comment by Markus23** [comment]
"commands.tpa.request": "Tpa request from %s",
 "commands.tpa.info": "/tpaccept /tpyes or /tpdeny /tpno",
 "commands.tpa.error": "You can not request your self ",
 "commands.tpa.youdenied":"youdenied",
 "commands.tpa.gotdenied":"gotdenied",
 "commands.tpa.nonetodeny":"nonetodeny",
 "commands.tpa.youaccepted": "youaccepted",
 "commands.tpa.gotaccepted": "gotaccepted",
 "commands.tpa.notonline": "notonline",
"commands.tpa.nonetoaccept":"nonetoaccept"

can you make the translation for the tpa command please

**Comment by XuyuEre** [comment]
oh?I didn't check that you updated the text, no problem, wait a minute.

**Comment by XuyuEre** [comment]
I finished

**Comment by Markus23** [comment]
Thanks

**Pull request merged**
